### ISSUE TITLE
Shocker Brute invisible.

### ISSUE THREAD

**Issue by Roet718** [SomeDeadGuy/UndeadPeopleTileset#31] opened 2020-10-29 11:37 UTC
For some reason shocker brutes are appearing as invisible while other cdda zombies appear fine. The ! sees you marker does appear where the zombie is though.

**Comment by SomeDeadGuy** [comment] 2020-10-30 04:56
I see no such thing. 
Shocker brute is animated, and all of it's frames is animated.
What version of the game are you using?

**Comment by Roet718** [comment] 2020-10-30 06:48
I am keeping up to date on the latest experimental so at the moment  build 11128. I have noticed some other shocker zombies will be invisible too until they die. I am using  Aftershock, Arcana, Blaze industries, CRIT and Magiclysm mods.

**Comment by SomeDeadGuy** [comment] 2020-10-30 07:37
I am saying on what OS do you play. As a said, dude. I just downloaded this tileset, latest version of the game (11130 now).
Installed them both in sepatate folder and electrical zombies are still there and animated.

**Comment by SomeDeadGuy** [comment] 2020-10-30 07:45
Here they are. Shocking away.
![Capture](https://user-images.githubusercontent.com/37592026/97673519-f3a79a80-1a9c-11eb-8409-b8ff19c1e2da.PNG)

**Comment by Roet718** [comment] 2020-10-30 07:59
OS  Windows 10. Ill try and get a screen shot.

**Comment by Roet718** [comment] 2020-10-30 08:08
Ok so I updated to 11130 made a new world and spawned the 3 shocker types in. This is what it looks like.
![3shockers](https://user-images.githubusercontent.com/19896899/97675355-2af65700-1a5d-11eb-9b90-f900c2bb5997.PNG)

**Comment by Roet718** [comment] 2020-10-30 08:12
repeated the test in a new world without any mods and the issue persists.

**Comment by Roet718** [comment] 2020-10-30 08:37
Just remembered that graphical overmap had me change the fonts.json file with their version. Went back and restored the file to the original version and the shockers appear now. Since the overmap doesn't seem to work without the file replacement i guess the mods are incompatible. 



[Graphical Overmap's Font.json and Readme.zip](https://github.com/SomeDeadGuy/UndeadPeopleTileset/files/5463910/Graphical.Overmap.s.Font.json.and.Readme.zip)

**Comment by SomeDeadGuy** [comment] 2020-10-30 08:40
Download and install in separate folder. Main game and tileset only.
No, graphical overmap and fonts also has nothing to dk with that (i think).
I am using Graphical Overmap mod and replaced my font json for it.
I will try and do that on fresh install too tho, to make sure.

**Comment by SomeDeadGuy** [comment] 2020-10-30 08:53
Nope. Installed Graphical Overmap, Magiclysm and Magyclysm graphical overmap and all of then work.  Animation showing, map looks graphical.
I have no idea what is going on with your game. All i can recommend is fresh install.

**Comment by Roet718** [comment] 2020-10-30 09:10
Ok so i made a fresh install and starting testing and at first i got the same results as you, everything was working.  Up until i  finally added your graphical mods for arcana .crit, magiclysm, aftershock ,mma and blaze industries. Once i added those mods into a new world  the shockers started being invisible. Ill test further to see if i can find which  of your patch mods is conflicting.

**Comment by Roet718** [comment] 2020-10-30 09:42
Well im stumped. when i started pulling out mods to test it the issue stopped occurring, even when i put all the mods back in.  Since then ive been unable to reproduce the issue.  On the bright side i managed to replicate the effect on my old install by yanking out the arcana/undead patch mod, loading up the game, shutting it down, and putting it back in, now shockers appear in all their animated glory.

**Comment by DenJur** [comment] 2020-10-30 14:45
Have the same issue. For me removing ArcanaUDP fixed it and adding it back in breaks it consistently.

**Comment by DenJur** [comment] 2020-10-30 22:59
Looks like arcana patch mode has a whole bunch of base game content redefined in it for some reason and I guess game doesn't like animated->static image redefining or perhaps sprite redifining in general (sortof similar problem as #34)

**Comment by Theawesomeboophis** [comment] 2020-10-31 02:18
Are you using regular Arcana or did you get it from Goat God, because if It's the latter, updating should fix the problem.

**Comment by Theawesomeboophis** [comment] 2020-10-31 02:20
Try and figure out where the glitch comes from, UndeadPeople or otherwise.

**Comment by Theawesomeboophis** [comment] 2020-10-31 02:30
I will test this , as I have chaosvolt arcana and I want to see if I get the same glitch.

**Comment by Theawesomeboophis** [comment] 2020-10-31 02:34
I got the same glitch, so it is not a Goat God issue, it might be fixed by installing Goat God version though.

**Comment by Theawesomeboophis** [comment] 2020-10-31 02:42
This is a tileset error, I tried with both versions of arcana, playing with Goat God version brings back regular shocker, but other variants are still invisible.

**Comment by DenJur** [comment] 2020-10-31 02:54
I already described where I think the glitch comes from. In #34 the sprite was initially loaded from original mods UltiCa set and then got redefined/reloaded from UDP at a smaller resolution. This resulted in some failure where original sprite remained but was truncated. In this case an animated sprite is loaded by the base UDP tileset and then gets overwritten by non-animated version from the ArcanaUDP mod and this results in no working sprite at all. 
I might be compleatly wrong on this because I don't know much about how tilesets work in Cataclysm so I left it for @SomeDeadGuy to take a look. This might be a problem in how the base game loads those sprites and if that's the case I assume he will open an issue on the base Cata repository.

**Comment by Theawesomeboophis** [comment] 2020-10-31 03:15
Switching to legacy fixes it, you could use legacy as a temporary fix until New Version is fixed.

**Comment by Theawesomeboophis** [comment] 2020-10-31 03:16
It's a problem with new version as far as I can tell, maybe SDG accidentally didn't set the tiles to target new or something.

**Comment by Roet718** [comment] 2020-10-31 23:31
Wow, im glad some smarter people than me were able to reproduce this and narrow it down, cuz i was at my wits end. Would it be better to use legacy version or just not use the arcana/udp patch until this is fixed, because arcana doesnt seem to have that many tiles anyway.

**Comment by Roet718** [comment] 2020-10-31 23:40
Oh, actually the latest version of UDP fixes with issue with arcana for me.

**Comment by Theawesomeboophis** [comment] 2020-11-01 02:09
I am on latest version, it's still not fixed for me, how did you get it to fix?

**Comment by Theawesomeboophis** [comment] 2020-11-01 02:14
should I try deleting arcana mod tileset instead of replacing, and then just add new version?

**Comment by Roet718** [comment] 2020-11-01 02:21
replacing the arcana/udp patch with the version in the newest udp update fixed it for me. But it looks like it was only temporary shockers have become invisible again.

**Comment by Theawesomeboophis** [comment] 2020-11-01 02:33
Yeah, it broke for me as well, my suggestion is to use legacy for now, as latest update made all mod tilesets compatible with legacy and I believe the only tiles that will be missing that are in new version are the vanilla tiles.

**Comment by SomeDeadGuy** [comment] 2020-11-01 09:20
Check fixed tileset mod in my mods.
I notified Kenan to fix it in his compilation.

**Comment by SomeDeadGuy** [comment] 2020-11-01 09:59
I can replicate the problem now. Gonna see what is going on.

**Comment by DenJur** [comment] 2020-11-01 13:35
Issue still exists with the latest master

**Comment by Theawesomeboophis** [comment] 2020-11-01 13:36
So its a problem with one of the modpacks?

**Comment by Theawesomeboophis** [comment] 2020-11-01 13:43
I have tested on Goat God, Chaosvolt version, and Kenan modpack, and the issue is present on all 3, so I believe it is a problem with the Chaosvolt mod tileset.

**Comment by SomeDeadGuy** [comment] 2020-11-01 14:52
sorry, error on my end
i made the fix but not uploaded it

**Comment by DenJur** [comment] 2020-11-01 16:10
Can confirm fix with the new version. Thank you!

**Comment by Theawesomeboophis** [comment] 2020-11-01 16:57
Problem was not fixed for me, but just realized I didn't have new kenan update, gonna update and try again.

**Comment by Theawesomeboophis** [comment] 2020-11-01 17:08
What version of Arcana are you using, because it's still broken on kenan, new update did bring back skeletal shocker but not the others.

**Comment by SomeDeadGuy** [comment] 2020-11-01 17:21
I use kenan version

**Comment by Roet718** [comment] 2020-11-01 22:00
Seems to be fixed on my version.

**Comment by Theawesomeboophis** [comment] 2020-11-01 23:07
Going back to either Goat God or Chaosvolt versions, don't know what's going on with my game.

**Comment by Theawesomeboophis** [comment] 2020-11-01 23:10
I'll try reinstalling Kenan version.

**Comment by Theawesomeboophis** [comment] 2020-11-01 23:54
Still broken for me, gonna use legacy for now, only skeletal shocker shows up for me.

**Comment by SomeDeadGuy** [comment] 2020-11-02 04:43
Dude, please join discord. 
There we can talk without gaps in 11 hours.

**Comment by SomeDeadGuy** [comment] 2020-11-05 05:03
Closing, since it was fixed.

**Closed by SomeDeadGuy** 2020-11-05 05:03 UTC
